const AppErrorCodes = {
  Continue: 100,
  Switching_Protocols: 101,
  Processing: 102,
  Early_Hints: 103,
  OK: 200,
  Created: 201,
  Accepted: 202,
  Non_Authoritative_Information: 203,
  No_Content: 204,
  Reset_Content: 205,
  Partial_Content: 206,
  Multi_Status: 207,
  Already_Reported: 208,
  IM_Used: 226,
  Multiple_Choices: 300,
  Moved_Permanently: 301,
  Found: 302,
  See_Other: 303,
  Not_Modified: 304,
  Use_Proxy: 305,
  Switch_Proxy: 306,
  Temporary_Redirect: 307,
  Permanent_Redirect: 308,
  BadRequest: 400,
  Unauthorized: 401,
  PaymentRequired: 402,
  Forbidden: 403,
  NotFound: 404,
  MethodNotAllowed: 405,
  NotAcceptable: 406,
  ProxyAuthenticationRequired: 407,
  RequestTimeout: 408,
  Conflict: 409,
  Gone: 410,
  LengthRequired: 411,
  PreconditionFailed: 412,
  PayloadTooLarge: 413,
  URITooLong: 414,
  UnsupportedMediaType: 415,
  RangeNotSatisfiable: 416,
  ExpectationFailed: 417,
  ImATeapot: 418,
  MisdirectedRequest: 421,
  UnprocessableEntity: 422,
  Locked: 423,
  FailedDependency: 424,
  UpgradeRequired: 426,
  PreconditionRequired: 428,
  TooManyRequests: 429,
  RequestHeaderFieldsTooLarge: 431,
  UnavailableForLegalReasons: 451,
  InternalServerError: 500,
  NotImplemented: 501,
  BadGateway: 502,
  ServiceUnavailable: 503,
  GatewayTimeout: 504,
  HTTPVersionNotSupported: 505,
  VariantAlsoNegotiates: 506,
  InsufficientStorage: 507,
  LoopDetected: 508,
  NotExtended: 510,
  NetworkAuthenticationRequired: 511,
};

const AppErrorCodeMessages = {
  Continue: "Continue",
  Switching_Protocols: "Switching Protocols",
  Processing: "Processing",
  Early_Hints: "Early Hints",
  OK: "OK",
  Created: "Created",
  Accepted: "Accepted",
  Non_Authoritative_Information: "Non-Authoritative Information",
  No_Content: "No Content",
  Reset_Content: "Reset Content",
  Partial_Content: "Partial Content",
  Multi_Status: "Multi-Status",
  Already_Reported: "Already Reported",
  IM_Used: "IM Used",
  Multiple_Choices: "Multiple Choices",
  Moved_Permanently: "Moved Permanently",
  Found: "Found",
  See_Other: "See Other",
  Not_Modified: "Not Modified",
  Use_Proxy: "Use Proxy",
  Switch_Proxy: "Switch Proxy",
  Temporary_Redirect: "Temporary Redirect",
  Permanent_Redirect: "Permanent Redirect",
  BadRequest: "Bad Request",
  Unauthorized: "Unauthorized",
  PaymentRequired: "Payment Required",
  Forbidden: "Forbidden",
  NotFound: "Not Found",
  MethodNotAllowed: "Method Not Allowed",
  NotAcceptable: "Not Acceptable",
  ProxyAuthenticationRequired: "Proxy Authentication Required",
  RequestTimeout: "Request Timeout",
  Conflict: "Conflict",
  Gone: "Gone",
  LengthRequired: "Length Required",
  PreconditionFailed: "Precondition Failed",
  PayloadTooLarge: "Payload Too Large",
  URITooLong: "URI Too Long",
  UnsupportedMediaType: "Unsupported Media Type",
  RangeNotSatisfiable: "Range Not Satisfiable",
  ExpectationFailed: "Expectation Failed",
  ImATeapot: "I'm a Teapot",
  MisdirectedRequest: "Misdirected Request",
  UnprocessableEntity: "Unprocessable Entity",
  Locked: "Locked",
  FailedDependency: "Failed Dependency",
  UpgradeRequired: "Upgrade Required",
  PreconditionRequired: "Precondition Required",
  TooManyRequests: "Too Many Requests",
  RequestHeaderFieldsTooLarge: "Request Header Fields Too Large",
  UnavailableForLegalReasons: "Unavailable For Legal Reasons",
  InternalServerError: "Internal Server Error",
  NotImplemented: "Not Implemented",
  BadGateway: "Bad Gateway",
  ServiceUnavailable: "Service Unavailable",
  GatewayTimeout: "Gateway Timeout",
  HTTPVersionNotSupported: "HTTP Version Not Supported",
  VariantAlsoNegotiates: "Variant Also Negotiates",
  InsufficientStorage: "Insufficient Storage",
  LoopDetected: "Loop Detected",
  NotExtended: "Not Extended",
  NetworkAuthenticationRequired: "Network Authentication Required",
};

module.exports = function (options) {
  options = options || {};
  options.code = options.code || AppErrorCodes.InternalServerError;
  options.message = options.message || AppErrorCodeMessages[options.code];
  return options;
};
